#!/bin/bash
#m10k_build_plugin test file

# Unpack source
tar xf mariadb*t*z

# Goes into project directorry
cd mariadb-[0-9]*

# Create a new directory for an out-of-source build (recommended when using cmake)
mkdir build
cd build

# Read configuration to be tested
read PERMUTATION

# Set the install directory.
INSTDIR=$HOME/bin/mariadb

# Set the compiler
CC=gcc

# Set FLAGS to the options from permutation
CFLAGS="$PERMUTATION -g -DNDEBUG"

# Set the installation layout options
CMAKE_LAYOUT_OPTS="-DCMAKE_INSTALL_PREFIX=$INSTDIR -DMYSQL_DATADIR=$INSTDIR/data"

# Set the feature options
CMAKE_FEATURE_OPTS="-DWITH_READLINE=1 -DWITHOUT_OQGRAPH_STORAGE_ENGINE=1"

# Set the build options
CMAKE_BUILD_OPTS="-DCMAKE_BUILD_TYPE=RelWithDebInfo"

# Run cmake in the build folder
cmake .. $CMAKE_BUILD_OPTS \
$CMAKE_LAYOUT_OPTS \
$CMAKE_FEATURE_OPTS \
-DCMAKE_C_FLAGS_RELWITHDEBINFO="$CFLAGS"

make -j13 && make install
