#!/bin/bash
#m10k_build_plugin test file

# Unpack source
tar xf mariadb*t*z

# Goes into project directorry
cd mariadb-[0-9]*

# Create a new directory for an out-of-source build (recommended when using cmake)
mkdir build
cd build

# Read configuration to be tested
read PERMUTATION

# Set the install directory.
INSTDIR=$HOME/bin

# Set FLAGS to the options from permutation
CFLAGS="$PERMUTATION"
CXXFLAGS="$CFLAGS"

# Set the installation layout options
# Info on options can be found in MariaDB's CMakeCache.txt
CMAKE_LAYOUT_OPTS="-DINSTALL_SCRIPTDIR=bin \
-DINSTALL_MYSQLDATADIR=var -DINSTALL_SBINDIR=libexec \
-DINSTALL_SUPPORTFILESDIR=share -DINSTALL_SYSCONFDIR=etc \
-DINSTALL_SYSCONF2DIR=etc/my.cnf.d -DCMAKE_INSTALL_PREFIX=$(INSTDIR) \
-DMYSQL_DATADIR=$(INSTDIR)/var"

# Set the feature options
# Info on options can be found in MariaDB's CMakeCache.txt
CMAKE_FEATURE_OPTS="-DWITH_READLINE=1 -DWITHOUT_OQGRAPH_STORAGE_ENGINE=1"

# Set the build options
# Info on options can be found in MariaDB's CMakeCache.txt
CMAKE_BUILD_OPTS="-DCMAKE_BUILD_TYPE=RelWithDebInfo"

# Run cmake in the build folder
CC=/usr/bin/gcc CXX=/usr/bin/gcc cmake .. $CMAKE_BUILD_OPTS \
$CMAKE_LAYOUT_OPTS \
$CMAKE_FEATURE_OPTS \
-DCMAKE_C_FLAGS_RELWITHDEBINFO="$CFLAGS" \
-DCMAKE_CXX_FLAGS_RELWITHDEBINFO="$CXXFLAGS" ||
exit $?

make -j9
